# Generated by Django 2.0.5 on 2018-06-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('zhi', models.CharField(choices=[('1', '一值'), ('2', '二值'), ('3', '三值'), ('4', '四值'), ('5', '五值'), ('0', '其他')], max_length=1, verbose_name='值别')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=32, verbose_name='菜名')),
            ],
            options={
                'verbose_name_plural': '所有菜单',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ManyToManyField(to='diancan.Dish')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diancan.Consumer', verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField()),
                ('time_quantum', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '夜宵')], max_length=9, verbose_name='时间段')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diancan.Dish')),
            ],
            options={
                'verbose_name_plural': '每日菜单',
            },
        ),
    ]
