# Generated by Django 2.0.5 on 2018-06-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish',
            new_name='name',
        ),
    ]
